package projectpl;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class userForm extends javax.swing.JFrame {

    /**
     * Creates new form userForm
     */
    public userForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_register1 = new javax.swing.JButton();
        btn_register3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_domainname = new javax.swing.JTextField();
        btn_clear2 = new javax.swing.JButton();
        btn_find = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        linkLogout = new javax.swing.JLabel();

        btn_register1.setBackground(new java.awt.Color(102, 102, 102));
        btn_register1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_register1.setForeground(new java.awt.Color(255, 255, 255));
        btn_register1.setText("Register");
        btn_register1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_register1.setBorderPainted(false);
        btn_register1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_register1MousePressed(evt);
            }
        });

        btn_register3.setBackground(new java.awt.Color(102, 102, 102));
        btn_register3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_register3.setForeground(new java.awt.Color(255, 255, 255));
        btn_register3.setText("Find");
        btn_register3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_register3.setBorderPainted(false);
        btn_register3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_register3MousePressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Find the IP address");

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        txt_domainname.setFont(new java.awt.Font("Urdu Typesetting", 1, 18)); // NOI18N
        txt_domainname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        txt_domainname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_domainnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_domainnameFocusLost(evt);
            }
        });
        txt_domainname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_domainnameActionPerformed(evt);
            }
        });

        btn_clear2.setBackground(new java.awt.Color(0, 153, 153));
        btn_clear2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_clear2.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear2.setText("Clear");
        btn_clear2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_clear2.setBorderPainted(false);
        btn_clear2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_clear2MousePressed(evt);
            }
        });
        btn_clear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear2ActionPerformed(evt);
            }
        });

        btn_find.setBackground(new java.awt.Color(0, 153, 153));
        btn_find.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_find.setForeground(new java.awt.Color(255, 255, 255));
        btn_find.setText("Find");
        btn_find.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_find.setBorderPainted(false);
        btn_find.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_findMousePressed(evt);
            }
        });
        btn_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter the domain name:");

        linkLogout.setBackground(new java.awt.Color(204, 204, 204));
        linkLogout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        linkLogout.setForeground(java.awt.Color.cyan);
        linkLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        linkLogout.setText("LogOut");
        linkLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkLogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_find, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btn_clear2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_domainname, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(linkLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linkLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txt_domainname, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_find, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_register1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_register1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_register1MousePressed

    private void btn_clear2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clear2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clear2MousePressed

    private void btn_register3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_register3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_register3MousePressed

    private void btn_findMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_findMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_findMousePressed

    private void txt_domainnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_domainnameFocusGained
//        if(txt_domainname.getText().trim().equals("Enter the domain name"))
//        {
//            txt_domainname.setText("");
//            txt_domainname.setForeground(Color.black);
//        }
    }//GEN-LAST:event_txt_domainnameFocusGained

    private void txt_domainnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_domainnameFocusLost
//        if(txt_domainname.getText().equals("") || txt_domainname.getText().equals("Enter the domain name"))
//        {
//            txt_domainname.setText("Enter the domain name");
//            txt_domainname.setForeground(new Color(153,153,153));
//        }
    }//GEN-LAST:event_txt_domainnameFocusLost

    private void txt_domainnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_domainnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_domainnameActionPerformed

    private void linkLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkLogoutMouseClicked
        loginForm lg = new loginForm();
        lg.setVisible(true);
        lg.pack();
        lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_linkLogoutMouseClicked

    private void linkLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkLogoutMouseEntered
        Border label1_Border = BorderFactory.createMatteBorder(0,0,1,0, Color.cyan);
        linkLogout.setBorder(label1_Border);
    }//GEN-LAST:event_linkLogoutMouseEntered

    private void linkLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkLogoutMouseExited
        linkLogout.setBorder(null);
    }//GEN-LAST:event_linkLogoutMouseExited

    private void btn_clear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear2ActionPerformed
        txt_domainname.setText("");
        txt_domainname.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_btn_clear2ActionPerformed

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
        user u1 = new user();
        String ip=u1.find(txt_domainname.getText());
        if(ip == "not found")
        {
            JOptionPane.showMessageDialog(null,"That domain name hasn't an IP Address");
        }
        else
            JOptionPane.showMessageDialog(null,"The IP Adress of "+txt_domainname.getText()+" is "+ip);
    }//GEN-LAST:event_btn_findActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear2;
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_register1;
    private javax.swing.JButton btn_register3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel linkLogout;
    private javax.swing.JTextField txt_domainname;
    // End of variables declaration//GEN-END:variables
}
